version: '3'

services:
  pgdb:
    image: postgres
    container_name: pg_server_api0121
    ports:
      - '9090:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api-starter-0121
      # Added this secret key for JwtUtils @Value("${jwt.secret}")
      - secret=sdQWfgio"$%^&£gjw£rgigh34i12gjwriogj43iotgyerujgergGERTHETHET35yh£hg£%GH£5gh4tyj46uhj46u£$%ethrtyjk567uj4hj4u$hEth345h34tHetH46h34hryHJ$h46h46k68K658jETghwHetJtuKLuilUt67yh$%y5£$£$%£%$^$^1234wewe354
    volumes:
      - ./docker/pg/postgres.conf:/etc/postgresql/postgresql.conf
      - ./data/pg:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - postgres
    restart: always

  pgadminFp:
    container_name: pgadmin_0121
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_SERVER_JSON_FILE: /tmp/.pgadmin/servers.json
    volumes:
      - ./data/pgadmin:/tmp/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5051}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
